export const ROLES = {
  PUBLIC: 'PUBLIC',
  RESEARCHER: 'RESEARCHER',
  GIS_OFFICER: 'GIS_OFFICER',
  GOVT_OFFICER: 'GOVT_OFFICER',
  ADMIN: 'ADMIN',
};

export const ROLE_LABELS = {
  [ROLES.PUBLIC]: 'Public User',
  [ROLES.RESEARCHER]: 'Researcher / Analyst',
  [ROLES.GIS_OFFICER]: 'GIS Field Officer',
  [ROLES.GOVT_OFFICER]: 'Govt. Officer / Policy Maker',
  [ROLES.ADMIN]: 'System Admin',
};

export const ROLE_DESCRIPTIONS = {
  [ROLES.PUBLIC]: 'Explore general information, view maps and access basic research.',
  [ROLES.RESEARCHER]: 'Access detailed research, datasets, reports and advanced analysis tools.',
  [ROLES.GIS_OFFICER]: 'Use spatial data, maps and field reporting tools for on-ground work.',
  [ROLES.GOVT_OFFICER]: 'Access policy documents, governance tools and decision support systems.',
  [ROLES.ADMIN]: 'Manage users, data and platform settings.',
};

export const MOCK_USERS = {
  PUBLIC: {
    id: 'usr_pub_01',
    name: 'Ratnadeep Nath',
    email: 'ratnadeepnath@gmail.com',
    phone: '+91 98765 43210',
    location: 'Nadia, West Bengal',
    joinedDate: '12 Mar 2025',
    role: ROLES.PUBLIC,
    organization: 'Citizen Access',
    designation: 'General Citizen / Public User',
    bio: 'Exploring land information, governance transparency, and public GIS maps.',
  },
  RESEARCHER: {
    id: 'usr_res_01',
    name: 'Dr. Ananya Roy',
    email: 'researcher@bhoomivision.demo',
    phone: '+91 98765 12345',
    location: 'Nadia, West Bengal',
    joinedDate: '15 Jan 2025',
    role: ROLES.RESEARCHER,
    organization: 'National Institute of Rural Development & Panchayati Raj',
    designation: 'Senior Land Research Analyst',
    bio: 'Specialist in multi-temporal LULC satellite analysis and land tenure governance.',
    verificationStatus: 'Verified Researcher',
    researchDomain: 'Land Use & Land Cover',
    researchInterests: ['Land Use', 'GIS', 'Agriculture', 'Land Governance', 'Policy'],
  },
  GIS_OFFICER: {
    id: 'usr_gis_01',
    name: 'Rajesh Kumar',
    email: 'gis.officer@bhoomivision.demo',
    phone: '+91 98765 99887',
    location: 'North 24 Parganas, West Bengal',
    joinedDate: '10 Feb 2025',
    role: ROLES.GIS_OFFICER,
    organization: 'Survey of India & State GIS Cell',
    designation: 'Senior GIS Field & Spatial Survey Officer',
    bio: 'Specialist in high-resolution drone cadastral surveys, satellite change detection, and on-ground land verification.',
    verificationStatus: 'Verified Field Officer',
  },
  GOVT_OFFICER: {
    id: 'usr_govt_01',
    name: 'Smt. Malini Banerjee',
    email: 'govt.officer@bhoomivision.demo',
    phone: '+91 98765 77665',
    location: 'West Bengal / New Delhi',
    joinedDate: '01 Jan 2025',
    role: ROLES.GOVT_OFFICER,
    organization: 'Ministry of Rural Development & Land Reforms Dept',
    designation: 'Joint Secretary & Policy Director',
    bio: 'Overseeing land policy innovation, evidence-based decision support, and national land reform implementation.',
    verificationStatus: 'Verified Government Officer',
  },
  ADMIN: {
    id: 'usr_admin_01',
    name: 'System Administrator',
    email: 'admin@bhoomivision.demo',
    phone: '+91 98765 00001',
    location: 'National Data Center / New Delhi',
    joinedDate: '01 Dec 2024',
    role: ROLES.ADMIN,
    organization: 'NIC / Ministry of Electronics & IT',
    designation: 'National Platform & Security Administrator',
    bio: 'Managing system roles, platform datasets, GIS layers, AI monitoring, and audit logs.',
    verificationStatus: 'Super Admin Access',
  },
};
